server:
  port: 8085
  tomcat:
    max-threads: 1000
    min-spare-threads: 0
logging:
    config: classpath:logback.xml
spring:
  application:
    name: xuwen-demo
  datasource:
    name: db
    url: jdbc:mysql://localhost:3306/bdp_user?useUnicode=true&characterEncoding=UTF8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 50
    initialSize: 5
    maxWait: 60000
    minIdle: 5
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    druid: #关闭监控 WebAppStat getSessionStat sessionStatMap
#      web-stat-filter:
#        session-stat-enable: false
#        profile-enable: false
#        enabled: false
      StatViewServlet:
#        reset-enable: false
        enabled: false
  redis:  
    database: 8 # Redis服务选库
    host: localhost # Redis服务器地址
    port: 6379  # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    pool:
      max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8  # 连接池中的最大空闲连接
      min-idle: 0  # 连接池中的最小空闲连接
      timeout:  0 # 连接超时时间（毫秒）
mybatis:
    type-aliases-package: com.xuwen.demo.dao.mapper
    mapper-locations: classpath:mapper/*.xml
mapper:
    mappers:
        - com.xuwen.demo.util.MyMapper
    not-empty: false
    identity: MYSQL
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
swagger:
  basePackage: com.xuwen.demo.controller
  enable: true
  service:
    name: demo服务
    description:
    developer: xuwen
    version: 1.0
security:
  basic:
    enabled: false
  user:
    name: dpc
    password: dpc.TmP